# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d9c523e9ea00eb29d58c9e794ad6be523dfc578f6883789752baf977e8f98f621b9e3c3b20c275884280f9aa61161e4461d48d6fb4557b8ff8048ec3ec97872

test:
  secret_key_base: e164f4c56486086b7c3e1797390ae414aae0cb87f5b7b8c12df2450e163799447325b42e03bdd1c250b2592b3f86400fd4eb20836f2622fc07122845607fb1a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
